id: I9A934698
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T17:02:06+00:00'
last_modified: '2022-06-16T04:22:50.255585+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30344
  title: གུ་རུ་དྲག་པོ་རྡོ་རྗེ་གྲོ་ལོད་ཀྱི་ཆོས་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    23D4:
      image_group_id: I1KG5768
      title: Volume 1 of bod kyi deb ther dpyid kyi rgyal mo'i glu dbyangs
      total_pages: 216
      order: 1
      base_file: 23D4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
