id: I9A934698
legacy_id: P000512
ocr_import_info:
  bdrc_scan_id: W30344
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T17:01:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:33:47.856061+00:00'
last_modified: 2022-09-03 19:33:55.627294
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30344
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30344
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གུ་རུ་དྲག་པོ་རྡོ་རྗེ་གྲོ་ལོད་ཀྱི་ཆོས་སྐོར།
  author: ཨ་འཛོམ་འབྲུག་པ་འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7439890876872086
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I6140:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6140
      total_pages: 584
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6140.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.7439890876872086
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
